import {
  FaArrowLeft,
  FaArrowRight,
  FaBars,
  FaBookmark,
  FaCamera,
  FaComment,
  FaDownload,
  FaEye,
  FaFilter,
  FaHeart,
  FaHouse,
  FaLocationDot,
  FaMagnifyingGlass,
  FaPen,
  FaRotateRight,
  FaShare,
  FaTriangleExclamation,
  FaUser,
  FaUserPlus,
  FaXmark,
} from "react-icons/fa6";

export const ICONS = {
  home: FaHouse,
  search: FaMagnifyingGlass,
  pen: FaPen,
  location: FaLocationDot,
  user: FaUser,
  camera: FaCamera,
  bars: FaBars,
  xmark: FaXmark,
  filter: FaFilter,
  arrowLeft: FaArrowLeft,
  arrowRight: FaArrowRight,
  heart: FaHeart,
  comment: FaComment,
  share: FaShare,
  bookmark: FaBookmark,
  userPlus: FaUserPlus,
  download: FaDownload,
  eye: FaEye,
  rotateRight: FaRotateRight,
  warning: FaTriangleExclamation,
} as const;

export type IconName = keyof typeof ICONS;
